# -*- coding: utf-8 -*-
"""BlenderRender.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/aniquetahir/Colaboratory/blob/master/BlenderRender.ipynb

# Blender Render Script for Colab
This is a script for rendering in blender using Google Collab

## Steps
- Make sure you have GPU enabled in your kernel (Also ensure that your blend file has GPU enabled)
- Use wget to download your file into the kernel
- In the blender command make sure that the correct filename is provided
"""

#@title Blender Parameters
download_file_path = 'https://s3-us-west-2.amazonaws.com/anique/blenderfiles/RiyoGudako.blend' #@param {type: "string"}
filename = 'Gudako' #@param {type: "string"}
filename+= '.blend'
renderer = "CYCLES" #@param ["CYCLES", "BLENDER_RENDER"]
frame = 1  #@param {type: "number"}

!apt install blender
!apt install libboost-all-dev
!apt install libgl1-mesa-dev

!wget -O $filename $download_file_path

!ls -la

!blender -b $filename -noaudio -o ./test_ -E $renderer -x 1 -f $frame

from IPython.display import Image

Image(filename='./test_0001.png')

