name: test
on: [push]
jobs:
  test:
    runs-on: [ubuntu-18.04]
    steps:
      - name: remote-bash
        uses: shinhwagk/remote-bash@0.0.1
        with:
          args: |
            git clone https://github.com/Sam2much96/Auto-ier
          
   
          
        env:
          REMOTE_BASH_URL : https://raw.githubusercontent.com/shinhwagk/remote-bash/master/test.sh
      
           
            

            
