name: run-script
on: push

 
jobs:
  release:
    runs-on: ubuntu-latest
  
    steps:
      - name: script
        uses: shinhwagk/remote-bash@0.0.1
        with: 
          args: sudo apt update
            

            
